version: '3'
services:
    traefik:
        image: traefik:v2.2
        command:
            - "--api.insecure=true"
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
        ports:
            - "80:80"
            - "8082:8080"
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - frontback
    whoami:
        image: "traefik/whoami"
        container_name: "simple-service"
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
            - "traefik.http.routers.whoami.entrypoints=web"
        networks:
            - frontback
    nginx:
        build: .
        ports:
            - "8080:80"
        networks:
            - frontback
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.nginx.rule=Host(`nginx.localhost`)"
            - "traefik.http.routers.nginx.entrypoints=web"
    apache:
        image: httpd:latest
        ports:
            - "8081:80"
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "3306:3306"
        volumes :
            - ./mysql:/var/lib/mysql
        networks:
            - frontback
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./mongodb:/data/db
        networks:
            - frontback
    flaskapp:
        build: ./flask_app/
        ports:
            - "5000:5000"

networks:
    frontback:

volumes:
    mysql:
    mongodb: