version: '3'
services:
    nginx:
        build: .
        ports:
            - "8080:80"
        networks:
            - frontback
    apache:
        image: httpd:latest
        ports:
            - "8081:80"
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "3306:3306"
        volumes :
            - ./mysql:/var/lib/mysql
        networks:
            - frontback
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
    mongodb:
        image: mongo:latest
        ports:
            - "27017:27017"
        volumes:
            - ./mongodb:/data/db
        networks:
            - frontback
    flaskapp:
        build: ./flask_app/
        ports:
            - "5000:5000"

networks:
    frontback:

volumes:
    mysql:
    mongodb: